---
layout: publication
title: "A Time-series Data Generation Tool for Risk Assessment of Robotic Applications"
authors: "Yuliang Ma, Apurv Patel, Don Kurian, Julien Siebert, Silvia Vock, Andrey Morozov"
date: "2025-01-01"
description: "Robotic systems increasingly rely on artificial intelligence (AI) to enhance their capabilities in performing complex tasks across various domains. 
The development and evaluation of AI systems usually require high-quality datasets"
link: "https://www.researchgate.net/publication/388116787_A_Time-series_Data_Generation_Tool_for_Risk_Assessment_of_Robotic_Applications"

---
