---
layout: publication
title: "The need for systematic approaches in risk assessment of safety-critical AI-applications in machinery"
authors: "Franziska Wolny, Silvia Vock, Rasmus Adler, Taras Holayad"
date: "2025.06.15"
journal: "Proceedings of the European Safey and Reliability Conference (ESREL), Stavanger/Norway"
description: "The integration of artificial intelligence (AI) into safety-critical machinery applications in industrial environments
presents substantial challenges for conformity assessment and safety certification."
link: "https://rpsonline.com.sg/proceedings/esrel-sra-e2025/html/ESREL-SRA-E2025-P7168.html"


---
