---
layout: publication
title: "The need for systematic approaches in risk assessment of safety-critical AI-applications in machinery"
authors: "Franziska Wolny, Silvia Vock, Rasmus Adler, Taras Holayad"
date: ""
journal: "Prceedings of the European Safey and Reliability Conference (ESREL), Stavanger/Norway,June 2025"
description: "The integration of artificial intelligence (AI) into safety-critical machinery applications in industrial environments
presents substantial challenges for conformity assessment and safety certification."

---
